### ISSUE TITLE
Method of Generate

### ISSUE THREAD

**Issue by tengjiayan20** [sail-sg/FDM#1]
Excuse me. I wonder where the code of DPM-solver++ is as it is said to be used in the article.

**Comment by nickwzk** [comment]
Hi @tengjiayan20,
thanks for your attention. We've uploaded the DPM-Solver++ code.

**Comment by tengjiayan20** [comment]
@nickwzk 
Thanks for your replying! What about the hyperparameters of DPM-solver using in the experiments? Could you tell the exact setting?

**Comment by nickwzk** [comment]
We use the hyperparameters suggested in [DPM-Solver](https://github.com/LuChengTHU/dpm-solver), which is already provided in [generate.py](https://github.com/sail-sg/FDM/blob/main/generate.py).

**Comment by tengjiayan20** [comment]
Thanks for your replying!
